### ISSUE TITLE
releaseTag is not showing in dashboard for nativek8s project

### ISSUE THREAD

**Issue by w3aman** [mayadata-io/ci-e2e-dashboard#289]
in openebs.ci for native-k8s project release tag is coming as `NA`. it is only showing for ci tag 

pipeline link ref: https://gitlab.openebs.ci/openebs/e2e-nativek8s/-/jobs/233380

**Comment by bhaskarhc** [comment]
For native k8s Release tag unable to grep because of job name change happen , 

`ZFS-LocalPV PROVISIONER` --> `ZFS-LOCALPV-PROVISIONER-DEPLOY`

<img width="1434" alt="Screenshot 2020-07-13 at 2 12 07 PM" src="https://user-images.githubusercontent.com/40464957/87284286-d2359980-c513-11ea-9e1d-c3f3236aabd2.png">

**Comment by bhaskarhc** [comment]
https://github.com/mayadata-io/ci-e2e-status/pull/68
PR will fix the issue . 
@w3aman @gprasath Kindly review the PR

**Comment by w3aman** [comment]
For openebs.ci native-k8s project...jobname has been changed again, from which we are taking the release tag.
`ZFS-LOCALPV-PROVISIONER-DEPLOY ====> 2P01-ZFS-LOCALPV-PROVISIONER-DEPLOY`
because of this change. the tag name is coming as NA in openebs.ci
can  you please make change accordingly ? @bhaskarhc
